// Generated by scripts/train-confidence-model.mjs — do not edit by hand.
// Logistic-regression weights for the secret-confidence classifier. Trained
// offline on synthetic labelled data; shipped as fixed numbers so the library
// keeps its zero-dependency, deterministic runtime. Regenerate with:
//   node scripts/train-confidence-model.mjs --write
//
// Holdout: acc=98.80%  precision=99.05%  recall=98.55%  f1=98.80%  logloss=0.0298  (n=4000, fp=19, fn=29)

export interface ConfidenceModel {
  readonly version: number;
  readonly features: readonly string[];
  readonly weights: readonly number[];
  readonly bias: number;
}

export const CONFIDENCE_MODEL: ConfidenceModel = {
  version: 1,
  features: ["log2Len","entropy","fracLower","fracUpper","fracDigit","fracSymbol","fracHex","vowelFrac","classTransitionRate","hasMixedClasses","maxRunFrac","structuredHexId","ctxSecret","ctxBenign"],
  weights: [2.712748,3.920866,-5.874776,5.484371,1.346649,-9.662469,-0.058102,8.500786,2.714721,-0.676255,-3.0573,-6.969532,5.6429,-5.446436],
  bias: -29.559382,
};
